version: '1.0'

build:
  steps:
    - name: Install Dependencies
      run: |
        npm install
    - name: Run Tests
      run: |
        npm test
    - name: Build Application
      run: |
        npm run build
    - name: Run Unit Tests
      run: |
        npm run test:unit
    - name: Run Integration Tests
      run: |
        npm run test:integration
